### ISSUE TITLE
Add methods to README and document the code.

### ISSUE THREAD

**Issue by pushkar-anand** [pushkar-anand/php-useful#5]
All methods in [EasyHeaders.php](https://github.com/pushkar-anand/php-useful/blob/master/src/EasyHeaders.php) needs to be documented according to [phpdoc syntax](http://docs.phpdoc.org/references/phpdoc/basic-syntax.html).
Also, all methods in [EasyHeaders.php](https://github.com/pushkar-anand/php-useful/blob/master/src/EasyHeaders.php) must be added to the README under EasyHeaders title.

Please comment here before taking the issue.

**Comment by jackey8616** [comment]
Hi @pushkar-anand , i would like to take this issue,
but i'm not so familiar with phpdoc syntax.
If there is anything missed, please let me know, i would like to fix it!

**Comment by pushkar-anand** [comment]
Thanks for the interest. It is very easy to follow the phpdoc syntax. For any method follow the below example to add the documentation.
```
    /**
     * Sends a 404 NOT FOUND header.
     */
    static function not_found()
    {
        header($_SERVER['SERVER_PROTOCOL'] . ' 404 NOT FOUND',
            true,
            404);
        exit();
    }
```
Read this [Getting started with phpdoc](http://docs.phpdoc.org/getting-started/your-first-set-of-documentation.html)

**Comment by jackey8616** [comment]
I have commit some code at [here](https://github.com/jackey8616/php-useful/commit/3ad390f95d7848c4a33d794b2ad16a5125f17435).
Maybe you can check it out to see are there anything missing.

**Comment by pushkar-anand** [comment]
Great send a pull request.

**Comment by jackey8616** [comment]
Let me paste every methods into README 😃
